language: php
php:
  - 5.6
  - 5.5

before_script:
    - composer self-update
    - composer install
    - app/console doctrine:database:create
    - app/console doctrine:schema:update --force
    - app/console hautelook_alice:fixtures:load -n

script:
  - phpunit -c app/