# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db:
            entity: { class: AppBundle\Entity\User, property: username }
#        hwi:
#            id: hwi_oauth.user.provider

    encoders:
            AppBundle\Entity\User:
                        algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /admin
                always_use_default_target_path: true
                use_referer: true
                target_path_parameter: /admin
                remember_me: true
            logout:
                path:   /logout
                target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }